/**
 * Pure CSS-emission helpers. No imports on purpose: this module transforms a
 * plain `name → value` map into CSS text, so both the library and the
 * standalone generation script can use it identically and deterministically.
 *
 * Token names are stored WITHOUT the leading `--`; these helpers add it.
 */

/** A flat map of token base-name (no `--`) → CSS value. */
export type VarMap = Record<string, string>;

const GENERATED_BANNER =
  '/* GENERATED by @enterprise-design/design-tokens — do not edit by hand. */';

/** Render `--name: value;` declaration lines at the given indent. */
export function renderVars(vars: VarMap, indent = '  '): string {
  return Object.entries(vars)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join('\n');
}

/**
 * Render a CSS rule block for one or more selectors sharing the same vars.
 * `indent` is the leading indent of the whole block (for nesting under a media
 * query); declarations are indented one level (2 spaces) further.
 */
export function renderBlock(selectors: string | readonly string[], vars: VarMap, indent = ''): string {
  const list = typeof selectors === 'string' ? [selectors] : selectors;
  const head = list.map((s) => `${indent}${s}`).join(',\n');
  return `${head} {\n${renderVars(vars, `${indent}  `)}\n${indent}}`;
}

/** Build the non-themed `tokens.css` (`:root { … }`), with a generated banner. */
export function buildTokensCss(vars: VarMap): string {
  return `${GENERATED_BANNER}\n${renderBlock(':root', vars)}\n`;
}

export { GENERATED_BANNER };
