packages:
  - 'packages/*'
  - 'apps/*'
onlyBuiltDependencies:
  - esbuild
minimumReleaseAgeExclude:
  - '@eslint/eslintrc@3.3.6'
  - '@eslint/js@9.39.5'
  - eslint@9.39.5
allowBuilds:
  esbuild: true
