import { useState } from 'react';

export interface PreviewImageProps {
  /** Experience id or demo slug — maps to `/previews/<id>.jpg`. */
  id: string;
  alt: string;
  className?: string;
}

/**
 * A committed build-time screenshot of a live world or demo sample
 * (`apps/gallery/public/previews/<id>.jpg`, generated by
 * `scripts/shoot-previews.mjs`). Renders nothing when the file is missing
 * (e.g. a world newer than the last shoot), so callers must keep a graceful
 * text-only fallback underneath.
 */
export function PreviewImage({ id, alt, className }: PreviewImageProps) {
  const [failed, setFailed] = useState(false);
  if (failed) return null;
  return (
    <img
      src={`/previews/${id}.jpg`}
      alt={alt}
      loading="lazy"
      onError={() => setFailed(true)}
      className={className}
    />
  );
}
